build:
  version: "1.0"

cards:
  message: "Welcome to Bank cards related prod APIs"
  contactDetails:
    name: "Alberto - Product Owner"
    email: "alberto.trabajo.es@gmail.com"
  onCallSupport:
    - 717715674
    - 693339937