build:
  version: "3.0"

cards:
  message: "Welcome to Bank cards related local APIs"
  contactDetails:
    name: "Alberto - Developer"
    email: "alberto.trabajo.es@gmail.com"
  onCallSupport:
    - 717715674
    - 693339937